input_text:
  kid_special_change_text: "Grandma pickup today"
  kid_dinner_text: "Pizza"
  kid_now_fallback: "Free Time"
  kid_next_fallback: "Check Board"
  kid_later_fallback: "Dinner"

input_boolean:
  kid_school_tomorrow: true

input_datetime:
  kid_bedtime: "20:30:00"
